### ISSUE TITLE
Keyboard navigation not working for non A-Z characters.

### ISSUE THREAD

**Issue by webbson** [lcdsantos/jQuery-Selectric#133]
We have several dropdowns where we list all cities in Sweden. Some of these cities have names with Swedish characters åäö (ÅÄÖ) and for these the keyboard navigation wont work. Is there any simple way to fix this?

**Comment by lcdsantos** [comment]
It seems to be working fine here.

Are you using the latest Selectric version?

Can you reproduce the problem on something like [JSFiddle](https://jsfiddle.net/)?

**Comment by gearsdigital** [comment]
I'm able to reproduce this issue. But had to change my keyboard-Layout in order to got it working.

### Fiddle
https://jsfiddle.net/sdt0nssq/

| Given  | Action | Expected | Result
| :-------| :----- | :--------- | :--------
| native german Keyboard, swedish layout | Pressing `ü` (results in `å`) | Hit Ålborg | no Hit
| native german Keyboard, german layout | Pressing `ö` | Hit Östersund | no Hit

**Comment by gearsdigital** [comment]
Maybe it would be a good idea to extend the [diacritics replacement](http://stackoverflow.com/a/18123985/294076) or may to make it configurable per option.

**Comment by lcdsantos** [comment]
I really don't want to include that huge table of characters inside the plugin. Maybe as a option, but still, I think the problem lies elsewhere.

I think what's happening is that event.keyCode returns 0 when is a unrecognizable key and that's making the search break.

Perhaps we could use something like [KeyboardEvent.Key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key), but we have to think about the cross-browser compatibility, since it's not supported everywhere.

Also, something I've learned now. We're safe to remove event.keyCode and use only event.which, since [jQuery normalizes that](http://api.jquery.com/category/events/event-object/).

**Comment by gearsdigital** [comment]
The problem is the JS regex implementation which is not unicode aware. It knows only the standard (low-byte) ASCII charset, including characters 0 to 127. ASCII is not designed to represent non-Western alphabets.

My approach would be to provide some basic diacritic replacement and allow the user to extend or replace the internal diacritic map. So it's up to the user which non latin characters are matched.

I'ld  try to go with [this regex](https://regex101.com/r/of1mTr/1) `[A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff]` which will match `å`, `Ü` or `è`.

[Others](https://github.com/select2/select2/blob/master/src/js/select2/diacritics.js) have to deal with it too...

**Comment by lcdsantos** [comment]
Okay, I was confused by some stuff. But I get it now.

It's safe to use these non-ASCII chars in the code? I don't know how that would behave on different file encodings.

**Comment by gearsdigital** [comment]
Comparing the current hidden input value with each items text was the first thing came into my mind too. A simple comparsion won't  work as `Ålborg === Ål` would result in `false`. So we need to decide what we want to do now.

Probably the easiest way would be just to look at the starting sequence. But -as we currently need to support IE7 and IE8- we are not able to use _fancy stuff_ like `.startsWith()` (introduced in ES2015) or `.indexOf()`. So, back to `RegExp` which doesn't work because of its limited unicode support.

It could be an option to provide a legacy build which [includes needed polyfills](https://github.com/mathiasbynens/String.prototype.startsWith/blob/master/startswith.js).

Could be so easy :)

```js
_this.items.map(function(elm, index) {
  if ( elm.slug.startsWith(val) && !elm.disabled ) {
    _this.highlight(i);
    return false;
  }
});
```

**Comment by lcdsantos** [comment]
Do we have unicode problems with this?

```js
var searchString = 'Ål';
var searchItems = 'Ålborg';

var regexp = new RegExp('^'+ searchString, 'i');
var result = regexp.test(searchItems);
```

**Comment by gearsdigital** [comment]
Yes this should work 👍

After some thinking, I'm not sure if the is the expected behavior. If `å` is somewhere in between this will not match anymore.

But I think we should just try it and waiting for some feedback :)
