### ISSUE TITLE
At bottom of page, selectricAbove not being applied

### ISSUE THREAD

**Issue by woodybepierced** [lcdsantos/jQuery-Selectric#79]
We implemented the plugin and things we're going great. The only issue we cam across that that the select lists we're not expanding upward when at the bottom, or close to the bottom, of the page. 

It doesn't look there is something special we should have to do to get this to work properly. Has there been issues with something interfering with this selectricAbove feature?

**Comment by tylerbeck** [comment]
This bug can be closed.  List items must be displayed in order for the height and open direction calculations to work as intended.  

For robustness, it could be useful to add the open class to the outer wrapper before calculating height so that any css styles that are dependent on the `selectricOpen` class will be applied.

eg:

```
            $outerWrapper.addClass(_this.classes.open);
            itemsHeight = $items.outerHeight();
            itemsInnerHeight = $items.height();
```
