### ISSUE TITLE
Dropdown not scrolling on Android device

### ISSUE THREAD

**Issue by chapster11** [lcdsantos/jQuery-Selectric#89]
I'm able scroll multiple items in a dropdown list using Selectric on all mobile platforms except Android. Has anyone else had this issue. I don't want to turn disableOnMobile on because we are using custom icons in each item in the list. Any work arounds to this.

**Comment by mikedumont** [comment]
Bit late to comment on this question, but i had the same issue. With the default android browser you can't scroll in the dropdown. 

This issue is caused by the default selectric styling, on the class "selectric-items" there is a negative z-index "-1" specified. I changed this to a positive z-index of "2" to fix the issue.

.selectric-items {
    display: none;
    position: absolute;
    top: 100%;
    left: 0;
    background: #FFF;
    border: 1px solid #dbd9cf;
    z-index: 2;
    box-shadow: 0 0 10px -6px;
}
