### ISSUE TITLE
optgroup selected ignored

### ISSUE THREAD

**Issue by vwasteels** [lcdsantos/jQuery-Selectric#91]
when using optgroup, if an element is selected before plugin init, the first ```<option>``` keep getting selected instead

example : 

```html
    <select tabindex="0">
      <option>Select with optgroup</option>
      <optgroup label="Group 1">
        <option>Option 1.1</option>
      </optgroup>
      <optgroup label="Group 2">
        <option selected="selected">Option 2.1</option>
        <option>Option 2.2</option>
      </optgroup>
      <optgroup label="Group 3" disabled="">
        <option disabled="">Option 3.1</option>
        <option disabled="">Option 3.2</option>
        <option disabled="">Option 3.3</option>
      </optgroup>
    </select>
```

this will show ```Select with optgroup``` as the selected item, with ```class="selected"``` on it.

**Comment by pianomansam** [comment]
This problem is caused by the selector for the selected option assuming the option is a direct child of the `<select>`, but with an optgroup it isn't a direct child. Furthermore, the code determined what the selected option is by determining its index. But this fails because it uses jQuery's `.index()` which returns the index of the option within the optgroup. I have a pull request that should be coming soon to fix this.

**Comment by vwasteels** [comment]
thanks
